[tox]
envlist =
    codestyle
    py312
    py311
    py310
    py39
    pkg_meta
    mypy
isolated_build = true
skip_missing_interpreters = true
minversion = 3.22

[testenv]
description = run the tests with pytest under {envname}
extras =
    test
commands =
    python3 -m pytest --junitxml=reports/junit-{envname}.xml
package = wheel
wheel_build_env = .pkg

[testenv:mypy]
description = run mypy static type checks
extras = test
deps =
    mypy
    types-jsonschema
commands =
    mypy --config-file=pyproject.toml topdown_tool

[testenv:codestyle]
description = review the code styles
passenv =
    {[testenv]passenv}
    PROGRAMDATA
skip_install = true
deps =
    pre-commit>=2.21
    pylint>=3.0.2
    rich
    pydantic
    jsonschema
commands =
    pre-commit run --show-diff-on-failure --all-files
    pylint topdown_tool

[testenv:pkg_meta]
description = check that the long description is valid
skip_install = true
deps =
    build[virtualenv]>=0.9
    check-wheel-contents>=0.4
    twine>=4.0.2
commands =
    python -m build -o {envtmpdir} -s -w .
    twine check {envtmpdir}{/}*
    check-wheel-contents --no-config {envtmpdir}

[testenv:blackduck-detect]
description = create blackduck detect report
allowlist_externals=*
passenv=BLACKDUCK_SVC_ACCOUNT_API_KEY
commands =
    bash -c 'pip freeze > requirements.txt'
    curl -s -L https://artifactory.arm.com/artifactory/synopsys-blackduck.detect-arm/detect-arm.sh -o detect_arm.sh
    chmod +x ./detect_arm.sh
    bash -c "VERSION=$(pip show topdown-tool | grep Version | awk '{print $2}'); ./detect_arm.sh \
      --blackduck.url=https://arm.app.blackduck.com \
      --detect.project.name=UPEG:topdown-tool \
      --blackduck.api.token=$BLACKDUCK_SVC_ACCOUNT_API_KEY \
      --detect.project.version.name=$VERSION \
      --detect.accuracy.required=NONE \
      --detect.tools=DETECTOR \
      --detect.source.path=. \
      --detect.python.pip.requirements.file=requirements.txt"

[testenv:blackduck-snippet-matching]
description = create blackduck snippet matching report
allowlist_externals=*
passenv=BLACKDUCK_SVC_ACCOUNT_API_KEY
commands =
    curl -s -L https://artifactory.arm.com/artifactory/synopsys-blackduck.detect-arm/detect-arm.sh -o detect_arm.sh
    chmod +x ./detect_arm.sh
    bash -c "export BDS_JAVA_HOME=/usr/lib/jvm/java-21-openjdk-arm64/; VERSION=$(pip show topdown-tool | grep Version | awk '{print $2}'); ./detect_arm.sh \
      --blackduck.url=https://arm.app.blackduck.com \
      --detect.project.name=UPEG:topdown-tool \
      --blackduck.api.token=$BLACKDUCK_SVC_ACCOUNT_API_KEY \
      --detect.project.version.name=$VERSION \
      --detect.source.path=. \
      --blackduck.trust.cert=true \
      --detect.cleanup=false \
      --detect.project.tags=snippet_scan \
      --detect.tools=SIGNATURE_SCAN \
      --detect.blackduck.signature.scanner.individual.file.matching=ALL \
      --detect.detector.search.continue=true \
      --detect.detector.search.depth=05 \
      --detect.impact.analysis.enabled=true \
      --detect.binary.scan.search.depth=05 \
      --detect.blackduck.scan.mode=INTELLIGENT \
      --detect.blackduck.signature.scanner.copyright.search=true \
      --detect.blackduck.signature.scanner.license.search=true \
      --detect.blackduck.signature.scanner.snippet.matching=SNIPPET_MATCHING \
      --detect.blackduck.signature.scanner.paths=./topdown_tool,./tests \
      --detect.blackduck.signature.scanner.upload.source.mode=true"
